/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs/troubleshooting'
import { Route as DocsRestoreASessionRouteImport } from './routes/docs/restore-a-session'
import { Route as DocsOffBoxCopiesRouteImport } from './routes/docs/off-box-copies'
import { Route as DocsHowItWorksRouteImport } from './routes/docs/how-it-works'
import { Route as DocsDoctorRouteImport } from './routes/docs/doctor'
import { Route as DocsCommandsRouteImport } from './routes/docs/commands'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsRestoreASessionRoute = DocsRestoreASessionRouteImport.update({
  id: '/restore-a-session',
  path: '/restore-a-session',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsOffBoxCopiesRoute = DocsOffBoxCopiesRouteImport.update({
  id: '/off-box-copies',
  path: '/off-box-copies',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsHowItWorksRoute = DocsHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsDoctorRoute = DocsDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/404': typeof R404Route
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/doctor': typeof DocsDoctorRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/off-box-copies': typeof DocsOffBoxCopiesRoute
  '/docs/restore-a-session': typeof DocsRestoreASessionRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/doctor': typeof DocsDoctorRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/off-box-copies': typeof DocsOffBoxCopiesRoute
  '/docs/restore-a-session': typeof DocsRestoreASessionRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/404': typeof R404Route
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/doctor': typeof DocsDoctorRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/off-box-copies': typeof DocsOffBoxCopiesRoute
  '/docs/restore-a-session': typeof DocsRestoreASessionRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/404'
    | '/docs/commands'
    | '/docs/doctor'
    | '/docs/how-it-works'
    | '/docs/off-box-copies'
    | '/docs/restore-a-session'
    | '/docs/troubleshooting'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/docs/commands'
    | '/docs/doctor'
    | '/docs/how-it-works'
    | '/docs/off-box-copies'
    | '/docs/restore-a-session'
    | '/docs/troubleshooting'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/404'
    | '/docs/commands'
    | '/docs/doctor'
    | '/docs/how-it-works'
    | '/docs/off-box-copies'
    | '/docs/restore-a-session'
    | '/docs/troubleshooting'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  R404Route: typeof R404Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/restore-a-session': {
      id: '/docs/restore-a-session'
      path: '/restore-a-session'
      fullPath: '/docs/restore-a-session'
      preLoaderRoute: typeof DocsRestoreASessionRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/off-box-copies': {
      id: '/docs/off-box-copies'
      path: '/off-box-copies'
      fullPath: '/docs/off-box-copies'
      preLoaderRoute: typeof DocsOffBoxCopiesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/how-it-works': {
      id: '/docs/how-it-works'
      path: '/how-it-works'
      fullPath: '/docs/how-it-works'
      preLoaderRoute: typeof DocsHowItWorksRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/doctor': {
      id: '/docs/doctor'
      path: '/doctor'
      fullPath: '/docs/doctor'
      preLoaderRoute: typeof DocsDoctorRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/commands': {
      id: '/docs/commands'
      path: '/commands'
      fullPath: '/docs/commands'
      preLoaderRoute: typeof DocsCommandsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsCommandsRoute: typeof DocsCommandsRoute
  DocsDoctorRoute: typeof DocsDoctorRoute
  DocsHowItWorksRoute: typeof DocsHowItWorksRoute
  DocsOffBoxCopiesRoute: typeof DocsOffBoxCopiesRoute
  DocsRestoreASessionRoute: typeof DocsRestoreASessionRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsCommandsRoute: DocsCommandsRoute,
  DocsDoctorRoute: DocsDoctorRoute,
  DocsHowItWorksRoute: DocsHowItWorksRoute,
  DocsOffBoxCopiesRoute: DocsOffBoxCopiesRoute,
  DocsRestoreASessionRoute: DocsRestoreASessionRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  R404Route: R404Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
